- name: Setting up server with DS viewer on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    - import_tasks: 03-setup_ds_viewer.yml
      tags: [setup_ds_viewer]

    - include_role:
        name: nginx
      vars:
        sites:
          ds_viewer:
            ssl_enabled: false
            external_port: "{{ ds_viewer.http_port }}"
            internal_port: "{{ ds_viewer.http_internal_port }}"
            internal_protocol: "http"
            domain: "{{ ds_viewer.domain }}"
          ds_viewer_secure:
            ssl_enabled: true
            external_port: "{{ ds_viewer.https_port }}"
            internal_port: "{{ ds_viewer.http_internal_port }}"
            internal_protocol: "http"
            domain: "{{ ds_viewer.domain }}"

  rescue:
    - debug:
        msg: "ERROR in Setting up server with DS viewer on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with DS viewer FINISHED on {{ inventory_hostname }}"
  tags: ["ds_viewer"]