- name: Setting up server with Cordra on {{ inventory_hostname }}
  block:

    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    - import_tasks: 03-setup_cordra.yml
      tags: [setup_cordra]

    - include_role:
        name: nginx
      vars:
        sites:
          cordra:
            ssl_enabled: false
            external_port: "{{ cordra.http_port }}"
            internal_port: "{{ cordra.http_internal_port }}"
            internal_protocol: "http"
            domain: "{{ cordra[instance_type].domain }}"
          cordra_secure:
            ssl_enabled: true
            external_port: "{{ cordra.https_port }}"
            internal_port: "{{ cordra.https_internal_port }}"
            internal_protocol: "https"
            domain: "{{ cordra[instance_type].domain }}"

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Cordra on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Cordra FINISHED on {{ inventory_hostname }}"
  tags: ["cordra"]